version: '3'
services:
    test-mongodb:
        image: mongo:4.0.8
        container_name: test-mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USER}"
            MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PWD}"
            MONGO_INITDB_DATABASE: ddictDB
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
        volumes:
            - ./test/data:/test/data
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
        ports:
            - "27017:27017"
